version: "3"
services:
 app:
  restart: always
  build: . # '点'代表当前目录
  command: 'python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000'
  ports:
   - "8000:8000"
   - "80:80"
  depends_on:
   - mysql
   - redis
  links:
   - mysql
   - redis
  working_dir: /home/docker/code/Keygene
  volumes:
    - $PWD/Keygene/:/Keygene
    - $HOME/Keygene/media:/home/docker/code/Keygene/media

 mysql:
  image: mysql:latest
  volumes:
    - $HOME/mysql:/var/lib/mysql
  ports:
    - "3306:3306"

 redis:
  image: redis:latest
  ports:
    - "6379"